/*
	VAZQUEZ, LEANDRO JAVIER
	DIV E
	EJERCICIO 01 WHILE
*/
function mostrar()
{
	// DECLARAMOS LA VARIABLE NUMERO
	let numero;

	// INICIALIZAMOS LA VARIABLE CON UN NUMERO PARA COMENZAR
	numero = 1;

	// AL WHILE LE PONEMOS LA CONDICION QUE SE REPITA HASTA QUE NUMERO LLEGUE A 10
	while(numero <= 10)
	{
		// MOSTRAMOS EL NUMERO POR CONSOLA
		console.log(numero);
		
		// A LA VARIABLE NUMERO DE LE SUMA 1
		numero = numero + 1; 
	}
}//FIN DE LA FUNCIÓN